### ISSUE TITLE
Very nice work

### ISSUE THREAD

**Issue by UncleGrumpy** [dimich-dmb/spi-ch341-usb#1] opened 2022-02-14 23:46 UTC
No problems with your repo at all so far. Just wanted to say thank you. I opened an Issue upstream about not compiling with kernel 5.16 and asked the author to merge your request (#20). Perhaps if you also open another issue we can get his attention.

I have not compared yet but does your PR included all of the improvements you have made since his work stopped? I see you have been doing work over these last few years to keep it current and documented.

**Comment by dimich-dmb** [comment] 2022-06-04 23:36
Hi @UncleGrumpy
Sorry, i just saw your message here. Since my first PR isn't merged i didn't create a new one with recent changes. Looks like the origin repo is abadoned.
Althrough i'm trying to keep backward-compatibility, i made some bugfixes and improvements (as i hope). I didn't test all possible use cases, so regression is possible. Feel free to report bugs if found.

**Closed as completed** 2022-06-04 23:36 UTC
